
[2019-06-02 19:38:18] Traceback (most recent call last):
  File "./src/010-image-crawler/main.py", line 229, in <module>
    app = App(root)
  File "./src/010-image-crawler/main.py", line 89, in __init__
    window_info.SetAsChild(self.get_window_handle(), rect)
NameError: name 'rect' is not defined


[2019-06-02 19:50:40] Traceback (most recent call last):
  File "./src/010-image-crawler/main.py", line 301, in <module>
    app = App(root)
  File "./src/010-image-crawler/main.py", line 91, in __init__
    self.browser_frame = BrowserFrame(self, self.navigation_bar)
AttributeError: 'App' object has no attribute 'navigation_bar'


[2019-06-03 11:11:19] Traceback (most recent call last):
  File "./src/010-image-crawler/tk_demo.py", line 377, in <module>
    main()
  File "./src/010-image-crawler/tk_demo.py", line 49, in main
    app = MainFrame(root)
  File "./src/010-image-crawler/tk_demo.py", line 72, in __init__
    self.setup_icon()
  File "./src/010-image-crawler/tk_demo.py", line 131, in setup_icon
    icon_path = os.path.join(resources, "tkinter"+IMAGE_EXT)
NameError: name 'IMAGE_EXT' is not defined


[2019-06-03 11:11:45] Traceback (most recent call last):
  File "./src/010-image-crawler/tk_demo.py", line 372, in <module>
    main()
  File "./src/010-image-crawler/tk_demo.py", line 49, in main
    app = MainFrame(root)
  File "./src/010-image-crawler/tk_demo.py", line 78, in __init__
    self.navigation_bar = NavigationBar(self)
  File "./src/010-image-crawler/tk_demo.py", line 265, in __init__
    back_png = os.path.join(resources, "back"+IMAGE_EXT)
NameError: name 'IMAGE_EXT' is not defined


[2019-06-03 11:28:59] Traceback (most recent call last):
  File "./src/010-image-crawler/main.py", line 188, in <module>
    app = App(root)
TypeError: __init__() takes 1 positional argument but 2 were given


[2019-06-03 11:29:13] Traceback (most recent call last):
  File "./src/010-image-crawler/main.py", line 187, in <module>
    app = App()
  File "./src/010-image-crawler/main.py", line 79, in __init__
    url='file://' + os.path.join(cur_dir, "ui", "index.html")
  File "cefpython_py37.pyx", line 682, in cefpython_py37.CreateBrowserSync
AssertionError: cefpython.CreateBrowserSync() may only be called on the UI thread


[2019-06-03 11:29:39] Traceback (most recent call last):
  File "./src/010-image-crawler/main.py", line 190, in <module>
    app.mainloop()
AttributeError: 'App' object has no attribute 'mainloop'


[2019-06-03 12:42:55] Traceback (most recent call last):
  File "./src/010-image-crawler/main.py", line 209, in <module>
    app = App()
  File "./src/010-image-crawler/main.py", line 99, in __init__
    from AppKit import NSApp
ModuleNotFoundError: No module named 'AppKit'


[2019-06-03 12:56:28] Traceback (most recent call last):
  File "./src/010-image-crawler/main.py", line 214, in <module>
    app = App()
  File "./src/010-image-crawler/main.py", line 73, in __init__
    self.image_loading = { "image": Image.open(os.path.join(dir_path, "loading.png"))}
UnboundLocalError: local variable 'os' referenced before assignment


[2019-06-03 13:03:09] Traceback (most recent call last):
  File "./src/010-image-crawler/main.py", line 198, in <module>
    app = App()
  File "./src/010-image-crawler/main.py", line 73, in __init__
    self.image_loading = { "image": Image.open(os.path.join(dir_path, "loading.png"))}
NameError: name 'Image' is not defined


[2019-06-03 13:08:46] Traceback (most recent call last):
  File "lifespan_handler.pyx", line 103, in cefpython_py37.LifespanHandler_DoClose
  File "./src/010-image-crawler/main.py", line 175, in DoClose
    self.__root.destroy()
AttributeError: 'load_handler' object has no attribute '_load_handler__root'


[2019-06-03 13:11:18] Traceback (most recent call last):
  File "lifespan_handler.pyx", line 103, in cefpython_py37.LifespanHandler_DoClose
  File "./src/010-image-crawler/main.py", line 175, in DoClose
    self.__root.destroy()
AttributeError: 'load_handler' object has no attribute '_load_handler__root'


[2019-06-03 15:38:08] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/010-image-crawler/main.py", line 153, in check_for_image_callback
    if queue_img_appraised.qsize()>0 and self.image_current == self.image_loading :
AttributeError: 'App' object has no attribute 'image_current'


[2019-06-03 15:46:21] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/010-image-crawler/main.py", line 150, in check_for_image_callback
    if queue_img_appraised.qsize() > 0 and self.image_current == self.image_loading:
AttributeError: 'App' object has no attribute 'image_current'


[2019-06-03 15:46:38] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/010-image-crawler/main.py", line 150, in check_for_image_callback
    if queue_img_appraised.qsize() > 0 and self.image_current == self.image_loading:
AttributeError: 'App' object has no attribute 'image_current'


[2019-06-03 16:10:51] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/010-image-crawler/main.py", line 143, in skip_image_callback
    self.display_next_image()
  File "./src/010-image-crawler/main.py", line 186, in display_next_image
    image_src = "data:{0};base64,{1}".format(self.get_descriptor_by_type(ext), img_str.decode("utf-8"))
  File "./src/010-image-crawler/main.py", line 205, in get_descriptor_by_type
    raise Exception("No support for ["+ext+"] Only Jpeg, Png and Gif images are supported.")
Exception: No support for [MPO] Only Jpeg, Png and Gif images are supported.


[2019-06-03 16:26:57] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/010-image-crawler/main.py", line 156, in check_for_image_callback
    self.display_next_image()
  File "./src/010-image-crawler/main.py", line 186, in display_next_image
    image_src = "data:{0};base64,{1}".format(conf.get_descriptor_by_type(ext), img_str.decode("utf-8"))
AttributeError: 'Configuration' object has no attribute 'get_descriptor_by_type'


[2019-06-03 16:56:16] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/010-image-crawler/main.py", line 141, in skip_image_callback
    if 'md5' in self.image_current.keys():
AttributeError: 'NoneType' object has no attribute 'keys'


[2019-06-03 16:56:29] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/010-image-crawler/main.py", line 141, in skip_image_callback
    if 'md5' in self.image_current.keys():
AttributeError: 'NoneType' object has no attribute 'keys'


[2019-06-10 22:38:25] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
TypeError: search_start_callback() missing 1 required positional argument: 'search_term'


[2019-06-10 22:40:19] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 85, in search_start_callback
    image_src = "data:{0};base64,{1}".format(conf.image_descriptor_by_type(ext), img_str.decode("utf-8"))
AttributeError: 'Configuration' object has no attribute 'image_descriptor_by_type'


[2019-06-12 00:24:49] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/010-image-crawler/main.py", line 149, in keep_image_callback
    self.display_next_image()
  File "./src/010-image-crawler/main.py", line 177, in display_next_image
    img = self.image_current["image"]
TypeError: 'NoneType' object is not subscriptable


[2019-06-12 00:29:29] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/010-image-crawler/main.py", line 149, in keep_image_callback
    self.display_next_image()
  File "./src/010-image-crawler/main.py", line 177, in display_next_image
    img = self.image_current["image"]
TypeError: 'NoneType' object is not subscriptable


[2019-06-12 00:33:36] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 77, in search_start_callback
    ext = img.format
AttributeError: 'NoneType' object has no attribute 'format'


[2019-06-12 00:33:58] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 77, in search_start_callback
    ext = img.format
AttributeError: 'NoneType' object has no attribute 'format'


[2019-06-12 00:34:56] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 77, in search_start_callback
    ext = img.format
AttributeError: 'NoneType' object has no attribute 'format'


[2019-06-12 00:35:05] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 77, in search_start_callback
    ext = img.format
AttributeError: 'NoneType' object has no attribute 'format'


[2019-06-12 15:55:15] Traceback (most recent call last):
  File "./src/020-image-labeling/main.py", line 104, in <module>
    app = App()
  File "./src/020-image-labeling/main.py", line 63, in __init__
    bindings.SetFunction("py_search_start_callback", self.search_start_callback)
AttributeError: 'App' object has no attribute 'search_start_callback'


[2019-06-12 15:58:07] Traceback (most recent call last):
  File "./src/020-image-labeling/main.py", line 108, in <module>
    app = App()
  File "./src/020-image-labeling/main.py", line 63, in __init__
    bindings.SetFunction("py_on_next_click_callback", self.on_next_click_callback)
AttributeError: 'App' object has no attribute 'on_next_click_callback'


[2019-06-12 15:59:11] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-image-labeling/main.py", line 89, in OnLoadEnd
    self.on_next_click_callback()
AttributeError: 'load_handler' object has no attribute 'on_next_click_callback'


[2019-06-12 16:01:14] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-image-labeling/main.py", line 90, in OnLoadEnd
    app.on_next_click_callback()
TypeError: on_next_click_callback() missing 1 required positional argument: 'labels_json'


[2019-06-12 16:35:26] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-image-labeling/main.py", line 88, in OnLoadEnd
    app.on_next_click_callback("ssss")
  File "./src/020-image-labeling/main.py", line 73, in on_next_click_callback
    self.image_current = queue_loaded.get()
NameError: name 'queue_loaded' is not defined


[2019-06-12 16:37:29] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-image-labeling/main.py", line 84, in OnLoadEnd
    app.on_next_click_callback("ssss")
  File "./src/020-image-labeling/main.py", line 74, in on_next_click_callback
    print(queue_candidates[self.current_index])
IndexError: index 0 is out of bounds for axis 0 with size 0


[2019-06-12 16:37:40] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-image-labeling/main.py", line 84, in OnLoadEnd
    app.on_next_click_callback("ssss")
  File "./src/020-image-labeling/main.py", line 74, in on_next_click_callback
    print(queue_candidates[self.current_index])
IndexError: index 1 is out of bounds for axis 0 with size 0


[2019-06-12 16:41:49] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-image-labeling/main.py", line 83, in OnLoadEnd
    app.on_next_click_callback("ssss")
  File "./src/020-image-labeling/main.py", line 73, in on_next_click_callback
    print(queue_candidates[self.current_index])
IndexError: list index out of range


[2019-06-12 16:57:46] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-image-labeling/main.py", line 93, in OnLoadEnd
    app.on_next_click_callback("ssss")
  File "./src/020-image-labeling/main.py", line 81, in on_next_click_callback
    path = os.path.join(self.__dir, md5)
AttributeError: 'App' object has no attribute '_App__dir'


[2019-06-12 18:07:44] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 87, in on_next_click_callback
    image_meta["labels"] = json.loads(labels)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list


[2019-06-12 18:08:33] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 88, in on_next_click_callback
    image_meta["labels"] = json.loads(labels)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list


[2019-06-12 18:09:08] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 89, in on_next_click_callback
    json.dump(image_meta, current_json)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 180, in dump
    fp.write(chunk)
AttributeError: 'str' object has no attribute 'write'


[2019-06-12 18:09:43] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 89, in on_next_click_callback
    json.dump(image_meta, current_json)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 180, in dump
    fp.write(chunk)
AttributeError: 'str' object has no attribute 'write'


[2019-06-12 18:13:34] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 90, in on_next_click_callback
    json.dump(image_meta, outfile, ident=4)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 176, in dump
    default=default, sort_keys=sort_keys, **kw).iterencode(obj)
TypeError: __init__() got an unexpected keyword argument 'ident'


[2019-06-12 22:45:47] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-image-labeling/main.py", line 119, in OnLoadEnd
    app.display_image()
  File "./src/020-image-labeling/main.py", line 99, in display_image
    with open(next_json) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '96ccd32d2c62c840.json'


[2019-06-12 22:55:42] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-image-labeling/main.py", line 107, in OnLoadEnd
    app.display_image()
  File "./src/020-image-labeling/main.py", line 97, in display_image
    image_meta = reader_worker.read(self.current_index)
  File "/Users/d023280/Documents/workspace/image-crawler/src/020-image-labeling/persistence/reader/impl.py", line 34, in read
    image_meta["image"] = Image.open(path)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '96ccd32d2c62c840.jpeg'


[2019-06-12 22:56:51] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-image-labeling/main.py", line 107, in OnLoadEnd
    app.display_image()
  File "./src/020-image-labeling/main.py", line 101, in display_image
    image_src = "data:{0};base64,{1}".format(conf.image_descriptor_by_type(ext), img_str.decode("utf-8"))
NameError: name 'ext' is not defined


[2019-06-12 22:57:21] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 87, in on_next_click_callback
    with open(os.path.join(self.exporter_dir, current_json), 'w') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: './data/labeled/96ccd32d2c62c840.json'


[2019-06-12 23:15:59] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/020-image-labeling/main.py", line 87, in py_next_click_callback
    self.display_image()
  File "./src/020-image-labeling/main.py", line 93, in display_image
    self.current_image_meta = reader_worker.read(self.current_image_index)
  File "/Users/d023280/Documents/workspace/image-crawler/src/020-image-labeling/persistence/reader/impl.py", line 33, in read
    image_meta["labels"] = image_meta["labels"]
KeyError: 'labels'


[2019-06-13 11:49:16] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/030-cropper/main.py", line 78, in py_crop_image_callback
    writer_worker.write(image_meta)
  File "/Users/d023280/Documents/workspace/image-crawler/src/030-cropper/persistence/exporter/impl.py", line 21, in write
    print(labels[0]["id"])
IndexError: list index out of range


[2019-06-13 11:54:28] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/030-cropper/main.py", line 78, in py_crop_image_callback
    writer_worker.write(image_meta)
  File "/Users/d023280/Documents/workspace/image-crawler/src/030-cropper/persistence/exporter/impl.py", line 26, in write
    img.crop((x, y, width, height)).save(os.path.join(self.__dir, id + "." + img.format.lower()))
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/Image.py", line 2007, in save
    save_handler(self, fp, filename)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 502, in _save
    _write_single_frame(im, fp, palette)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 403, in _write_single_frame
    im_out = _normalize_palette(im_out, palette, im.encoderinfo)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 391, in _normalize_palette
    used_palette_colors = _get_optimize(im, info)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 678, in _get_optimize
    max(used_palette_colors) > len(used_palette_colors)):
ValueError: max() arg is an empty sequence


[2019-06-13 11:56:11] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/030-cropper/main.py", line 78, in py_crop_image_callback
    writer_worker.write(image_meta)
  File "/Users/d023280/Documents/workspace/image-crawler/src/030-cropper/persistence/exporter/impl.py", line 26, in write
    img.crop((x, y, width, height)).save(os.path.join(self.__dir, id + "." + img.format.lower()), img.format)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/Image.py", line 2007, in save
    save_handler(self, fp, filename)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 502, in _save
    _write_single_frame(im, fp, palette)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 403, in _write_single_frame
    im_out = _normalize_palette(im_out, palette, im.encoderinfo)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 391, in _normalize_palette
    used_palette_colors = _get_optimize(im, info)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 678, in _get_optimize
    max(used_palette_colors) > len(used_palette_colors)):
ValueError: max() arg is an empty sequence


[2019-06-13 12:14:48] Traceback (most recent call last):
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 620, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'P'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py37.V8FunctionHandler_Execute
  File "./src/030-cropper/main.py", line 78, in py_crop_image_callback
    writer_worker.write(image_meta)
  File "/Users/d023280/Documents/workspace/image-crawler/src/030-cropper/persistence/exporter/impl.py", line 27, in write
    img.crop((x, y, x+width, y+height)).save(os.path.join(self.__dir, id + ".jpeg"), "JPEG")
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/Image.py", line 2007, in save
    save_handler(self, fp, filename)
  File "/Users/d023280/Documents/workspace/image-crawler/venv/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 622, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode P as JPEG


[2019-06-14 10:44:43] Traceback (most recent call last):
  File "load_handler.pyx", line 58, in cefpython_py37.LoadHandler_OnLoadEnd
  File "./src/020-labeler/main.py", line 110, in OnLoadEnd
    app.display_image()
  File "./src/020-labeler/main.py", line 94, in display_image
    self.current_image_meta = reader_worker.read(self.current_image_index)
  File "/Users/d023280/Documents/workspace/image-crawler/src/020-labeler/persistence/reader/impl.py", line 25, in read
    json_file_name = os.path.join(self.__exporter_dir, self.__input[index])
IndexError: list index out of range

